-- Tables

CREATE TABLE IF NOT EXISTS public.schema_migrations
(
    id SERIAL PRIMARY KEY,
    version VARCHAR(255) NOT NULL UNIQUE,
    applied_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.customers
(
    customerid integer NOT NULL,
    customername text COLLATE pg_catalog."default" NOT NULL,
    deleted boolean NOT NULL DEFAULT false,
    customergroup smallint,
    CONSTRAINT "Customer_pkey" PRIMARY KEY (customerid)
);

CREATE TABLE IF NOT EXISTS public.products
(
    productid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 9 ),
    productname text COLLATE pg_catalog."default" NOT NULL,
    itemprice numeric(8, 2) NOT NULL,
    imagefilename text COLLATE pg_catalog."default" NOT NULL,
    disabled boolean NOT NULL DEFAULT false,
    sorting smallint DEFAULT 100,
    CONSTRAINT "Products_pkey" PRIMARY KEY (productid)
);

CREATE TABLE IF NOT EXISTS public.sales
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "timestamp" timestamp with time zone NOT NULL DEFAULT now(),
    customerid integer NOT NULL,
    productid integer NOT NULL,
    quantity integer NOT NULL,
    solditemprice numeric(8, 2) NOT NULL,
    soldproductname text COLLATE pg_catalog."default",
    soldsum numeric(8, 2) GENERATED ALWAYS AS ((solditemprice * (quantity)::numeric)) STORED,
    CONSTRAINT "Sales_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ecotransfer
(
    salesid integer NOT NULL,
    "timestamp" timestamp with time zone NOT NULL DEFAULT now(),
    preupdatesum numeric(8, 2),
    attempts smallint DEFAULT 0,
    transferred boolean NOT NULL DEFAULT false,
    errormsg text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.mowingsections
(
    id serial NOT NULL,
    section_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    cutting_time_in_h real NOT NULL DEFAULT 0,
    disabled boolean NOT NULL DEFAULT false,
    CONSTRAINT mowingsections_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.mowingusers
(
    customerid integer NOT NULL,
    CONSTRAINT mowingusers_pkey PRIMARY KEY (customerid)
);

CREATE TABLE IF NOT EXISTS public.mowingactivities
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    timestamp timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    section_id integer NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT mowingactivities_pkey PRIMARY KEY (id),
    CONSTRAINT mowingactivities_section_id_fkey FOREIGN KEY (section_id)
        REFERENCES public.mowingsections (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT mowingactivities_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.customers (customerid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.mowingmaintenance
(
    id smallserial NOT NULL,
    maintenance_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    interval_h real NOT NULL,
    last_maintained_timestamp timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id integer,
    CONSTRAINT mowingmaintenance_pkey PRIMARY KEY (id),
    CONSTRAINT mowingmaintenance_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.customers(customerid)
);

-- Foreign Keys

DO $$ BEGIN
    ALTER TABLE public.ecotransfer
        ADD CONSTRAINT "FK_salesid" FOREIGN KEY (salesid)
        REFERENCES public.sales (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE INDEX IF NOT EXISTS ecotransfer_salesid_idx
    ON public.ecotransfer(salesid);

DO $$ BEGIN
    ALTER TABLE public.mowingusers
        ADD CONSTRAINT fk_customerid FOREIGN KEY (customerid)
        REFERENCES public.customers (customerid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE INDEX IF NOT EXISTS mowingusers_pkey_idx
    ON public.mowingusers(customerid);

CREATE INDEX IF NOT EXISTS sales_customerid_idx
    ON public.sales(customerid);

CREATE INDEX IF NOT EXISTS sales_timestamp_idx
    ON public.sales("timestamp");

CREATE INDEX IF NOT EXISTS mowingactivities_timestamp_idx
    ON public.mowingactivities("timestamp");

CREATE INDEX IF NOT EXISTS mowingactivities_section_id_idx
    ON public.mowingactivities(section_id);
-- Views

CREATE OR REPLACE VIEW public.todayssalesgrouped AS
 SELECT customers.customername,
    sales.soldproductname,
    sum(sales.quantity) AS sum
   FROM sales
     JOIN customers USING (customerid)
  WHERE CAST(sales."timestamp" AS date) = CURRENT_DATE
  GROUP BY sales.soldproductname, customers.customername
  ORDER BY (sum(sales.quantity)) DESC;

CREATE OR REPLACE VIEW public.purchasehistory AS
 SELECT sales.id,
    to_char((date_trunc('minute'::text, sales."timestamp") AT TIME ZONE CURRENT_SETTING('TIMEZONE')), 'DD/MM-YYYY HH24:MI'::text) AS "time",
    sales.quantity,
    sales.soldsum AS salessum,
    customers.customerid,
    customers.customername,
    sales.soldproductname AS productname,
    sales."timestamp"
   FROM sales
     JOIN customers USING (customerid)
  ORDER BY sales.id;

CREATE OR REPLACE VIEW public.lastmowed AS
 SELECT days,
    customername,
    section_name
   FROM ( SELECT DISTINCT ON (s.section_name) date_part('days'::text, now() - m.timestamp)::integer AS days,
            c.customername,
            s.section_name
           FROM mowingactivities m
             JOIN mowingsections s ON m.section_id = s.id
             JOIN customers c ON m.user_id = c.customerid
          WHERE m.status::text = '8/8'::text
          ORDER BY s.section_name, m.timestamp DESC) test
  ORDER BY days DESC;

CREATE OR REPLACE VIEW public.mowinghistory AS
 SELECT to_char(m.timestamp::date, 'dd/mm/yyyy'::text) AS date,
    c.customername,
    s.section_name,
    m.status
   FROM mowingactivities m
     JOIN mowingsections s ON m.section_id = s.id
     JOIN customers c ON m.user_id = c.customerid
  ORDER BY m.id DESC;

CREATE OR REPLACE VIEW public.maintenancestatus AS
 SELECT m.id,
    m.maintenance_type,
    m.interval_h,
    m.last_maintained_timestamp,
    c.customername AS maintained_by,
    COALESCE(SUM(
        s.cutting_time_in_h *
        CAST(SPLIT_PART(a.status, '/', 1) AS FLOAT) /
        CAST(COALESCE(NULLIF(SPLIT_PART(a.status, '/', 2), ''), '8') AS FLOAT)
    ), 0) AS used_h,
    m.interval_h - COALESCE(SUM(
        s.cutting_time_in_h *
        CAST(SPLIT_PART(a.status, '/', 1) AS FLOAT) /
        CAST(COALESCE(NULLIF(SPLIT_PART(a.status, '/', 2), ''), '8') AS FLOAT)
    ), 0) AS remaining_h
   FROM mowingmaintenance m
     LEFT JOIN mowingactivities a ON a.timestamp > m.last_maintained_timestamp
     LEFT JOIN mowingsections s ON a.section_id = s.id AND a.status != 'NotMowed'
     LEFT JOIN customers c ON m.user_id = c.customerid
  GROUP BY m.id, m.maintenance_type, m.interval_h, m.last_maintained_timestamp, c.customername
  ORDER BY m.id;
